In [1]:
import numpy as np
from sklearn.model_selection import KFold

In [2]:
X = np.array([[1, 2], [2, 3], [4, 5,], [6, 7]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)

2

In [3]:
print(kf)

KFold(n_splits=2, random_state=None, shuffle=False)


In [8]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    print(X_train)
    print("----------------")

[[4 5]
 [6 7]]
----------------
[[1 2]
 [2 3]]
----------------


In [5]:
X_train

array([[1, 2],
       [2, 3]])